export default {
  textTitleMain: '3rem',
  textTitleBanner: '3rem',
  textTitleSection: '2.2rem',
  textTitleParagraph: '2rem',
  textTitleCard: '2rem',
  textSubtitleCard: '1.8rem',
  textSmallSubtitle: '1.7rem',
  textPCard: '1.6rem',
  textSmallP: '1.3rem',
  textLabel: '1.5rem',
  textFloatLabel: '1.2rem',
  textInput: '1.5rem',
  textError: '1.2rem',
  family: {
    default: "'Open Sans', sans-serif",
    secundary: "'Montserrat', sans-serif",
  },
  weight: {
    ultraThin: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    bold: 700,
  },
  layers: {
    base: 10,
    overlay: 20,
    onTop: 30,
  },
  sizes: {
    xxsmall: '0.8rem',
    xsmall: '1.2rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    xxlarge: '4.8rem',
    huge: '5.6rem',
    xhuge: '6.4rem',
  },
  spacings: {
    xsmall: '0.8rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    xxlarge: '4.8rem',
    huge: '5.6rem',
    xhuge: '6.4rem',
  },
  transitions: {
    default: '0.3s ease-in-out',
    quick: '0.1s ease-in-out',
  },
};
